"""empty message

Revision ID: d70e68937dfd
Revises: 
Create Date: 2018-03-23 01:31:33.087091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd70e68937dfd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('exec_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_create_time'), 'task', ['create_time'], unique=False)
    op.create_index(op.f('ix_task_exec_time'), 'task', ['exec_time'], unique=False)
    op.create_index(op.f('ix_task_start_time'), 'task', ['start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_start_time'), table_name='task')
    op.drop_index(op.f('ix_task_exec_time'), table_name='task')
    op.drop_index(op.f('ix_task_create_time'), table_name='task')
    op.drop_table('task')
    # ### end Alembic commands ###
